apiVersion: v1
kind: Service
metadata:
  name: event-email-service
  labels:
    example: event-email-service
    app: event-email-service
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: event-email-service
    example: event-email-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: event-email-service
  labels:
    app: event-email-service
    example: event-email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-email-service
      example: event-email-service
  template:
    metadata:
      labels:
        app: event-email-service
        example: event-email-service
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/event-email-service:0.0.x for Docker Hub).
      - image: eu.gcr.io/kyma-project/example/event-email-service:0.0.2
        imagePullPolicy: IfNotPresent
        name: event-email-service
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 32Mi
