---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: call-ec-web-ui
  labels:
    app: call-ec-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-ec-web-ui
  template:
    metadata:
      name: call-ec-web-ui
      labels:
        app: call-ec-web-ui
    spec:
      containers:
      - name: call-ec-web-ui
        image: eu.gcr.io/kyma-project/example/call-ec-web-ui:0.0.2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: call-ec-web-ui
  labels:
    app: call-ec-web-ui
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: call-ec-web-ui

---
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
    name: call-ec-web-ui
spec:
    service:
      name: call-ec-web-ui
      port: 3000
    hostname: call-ec-web-ui
    authentication: []
