apiVersion: v1
kind: Service
metadata:
  name: http-db-service
  labels:
    example: http-db-service
spec:
  ports:
  - name: http
    port: 8017
  selector:
    example: http-db-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-db-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        example: http-db-service
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
      - image: eu.gcr.io/kyma-project/example/http-db-service:0.0.6
        imagePullPolicy: IfNotPresent
        name: http-db-service
        ports:
        - name: http
          containerPort: 8017
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 32Mi
        env:
        - name: dbtype
          # available dbtypes are: [memory, mssql]
          value: "memory"


