name: event-emitter
namespace: default
runtime: nodejs18
source:
    sourceType: git
    url: https://github.com/kwiatekus/examples.git
    repository: kyma-examples-repo
    reference: reflect-changes-in-cloudevents-api
    baseDir: /incluster_eventing/src/emitter-fn/
apiRules:
    - name: incoming-http-trigger
      service:
        host: incoming
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow