apiVersion: v1
data:
  alert.rules: |-
    groups:
    - name: pod-not-running-rule
      rules:
      - alert: http-db-service-is-not-running
        expr: absent(kube_pod_container_status_running{pod=~"^http-db-service(.*)"})
        for: 15s
        labels:
          severity: critical
        annotations:
          description: "http-db-service pod is not running"
          summary: "http-db-service pod is not running"
kind: ConfigMap
metadata:
  labels:
    prometheus: monitoring
    role: alert-rules
    example: monitoring-alert-rules
  name: http-db-service-alert-rules
